[package]
name = "ocsp-rs"
version = "0.1.0"
authors = ["gaochen9 <gaochen9@cnpc.com.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
